#!/usr/bin/env bash
# stolen from ThePrimeagen

selected=`cat ~/.cht-languages ~/.cht-commands | fzf`
if [[ -z $selected ]]; then
    exit 0
fi

read -p "Enter Query: " query

if grep -qs "$selected" ~/.cheat-languages; then
    query=`echo $query | tr ' ' '+'`
    tmux neww bash -c "echo \"curl cheat.sh/$selected/$query/\" & curl cheat.sh/$selected/$query & while [ : ]; do sleep 1; done"
else
    tmux neww bash -c "curl -s cheat.sh/$selected~$query | less"
fi


